server/src/index.ts
=> get route getting ready for deployment

README.md
Issue #15 
Changed the ReadMe Title.
More updates coming...
=> [FE] ReadMe name change

README.md
=> [BE] Added About, Techstack, Features andd Goals

README.md
=> [BE] Added LinkedIn

client/index.html, client/package.json, client/src/App.tsx, client/src/global-vars/Api-url.ts, client/src/main.tsx, client/src/pages/Home.tsx, client/src/pages/Login.tsx, client/src/pages/Profile.tsx, client/src/pages/Register.tsx
=> updating backend with frontends authnetication functionlaity

client/src/components/Home/NavBar.tsx, client/src/layout.tsx, client/src/pages/Home.tsx
=> [FE] NavBar Update

client/src/components/Home/Footer.tsx, client/src/components/Home/NavBar.tsx
After:
Desktop:
Mobile:
Tablet:
Still in progress ...
=> Made Footer Responsive

client/src/components/Buttons/HeroCTAButton.tsx, client/src/components/Home/CategoryBrowse/CategoryCard.tsx, client/src/components/Home/Enterprise/EnterpriseSuite.tsx, client/src/pages/Home.tsx
Changed the Red button to Green.
After:
=> [FE] Color updates 

client/src/components/Home/FindTalent/FindTalent.tsx
=> image link fixed

client/src/assets/front-end-data/menu_items.ts, client/src/components/Home/NavBar.tsx, client/src/components/NavBar/MenuItem.tsx
Added **menu_items** object to import nav links 🥳
=> [FE] Refactor MegaMenu

client/src/components/Home/Footer.tsx, client/src/contants/index.ts
=> [FE] Added Footer links

client/src/App.tsx, client/src/components/Forms/InputField.tsx, client/src/components/Forms/dropDownSelect.tsx, client/src/components/Profile_photo_upload.tsx, client/src/layout.tsx, client/src/pages/Login.tsx, client/src/pages/Register.tsx, client/tailwind.config.js
Updated **SigUp/Login Pages** with **Light/Dark Mode** 🥳
Light:
Dark:
=> Refactor tailwind

client/src/components/FindCompanyPage/NeedHelpCard.tsx, client/src/components/FindDeveloperPage/NeedHelpDevCard.tsx, client/src/components/Home/CategoryBrowse/CategoryCard.tsx, client/src/components/NavBar/MainMenu/FindCompany/Developer_list.tsx, client/src/components/NavBar/MainMenu/FindCompany/FindCompanyMain.tsx, client/src/components/NavBar/MainMenu/FindCompany/NeedHelp.tsx, client/src/components/NavBar/MainMenu/FindDeveloper/NeedHelpDev.tsx
=> Menu pages

README.md
=> Update Feature MVP

client/index.html, client/src/components/MainMenuPages/WhyDevConnectPage/FAQCard.tsx, client/src/pages/MainMenu/WhyDevConnect/FAQs.tsx, client/tailwind.config.js
=> [FE] FAQ Template ready

client/src/components/User/User_Top.tsx, client/src/components/User/User_layout.tsx, client/src/components/User/User_main.tsx, client/src/context.tsx, client/src/pages/Profiles/Dev_Profile/Profile.tsx, client/src/pages/Profiles/Dev_Profile/Profile_Dashboard.tsx, client/src/pages/Profiles/Dev_Profile/Profile_Main.tsx
fix same styles , and make profil page responsive
=> update same styling on profile page (responsive,.)

client/src/components/Chat/Chat_Main.tsx
=> [FE] Chat styling

client/src/components/User/User_drop_down.tsx
=> [FE] Dropdown Style

client/src/components/Home/NavBar.tsx, client/src/components/Home/UserProflieNav.tsx, client/src/components/NavBar/MenuItem.tsx, client/src/components/User/User_drop_down.tsx
=> Dropdown styling

client/src/common.types.ts, client/src/components/Buttons/Search.tsx, client/src/components/Forms/SkillSelection.tsx, client/src/components/ProjectsListingPage/Projects/Projectscontainer.tsx, client/src/components/User/User_Info_Update_Input.tsx, client/src/components/User/User_Side.tsx, client/src/components/User/User_Top.tsx, client/src/components/User/User_main.tsx, client/src/components/User/User_portfolio.tsx, client/src/components/User/User_skills.tsx, client/src/pages/Profiles/AllRatings.tsx, client/src/pages/Profiles/Dev_Profile/Profile_Dashboard.tsx, client/src/pages/Profiles/Rating.tsx, client/src/pages/Profiles/Single_Company_Page.tsx, client/src/pages/Profiles/Single_User_Page.tsx, server/src/controller/Rating-controllers/Raiting-controller.ts, server/src/controller/company-controllers/company-project-controller.ts, server/src/controller/user-controllers/User-CRUD-controller.ts, server/src/model/rating_model.ts
=> profile page update

client/src/components/Home/UserProflieNav.tsx
Improved size and Light/Dark updates
=> [FE] Styling update
